### ISSUE TITLE
error: the parameter type `T` may not live long enough [E0310]

### ISSUE THREAD

**Issue by viperscape** [TyOverby/bchannel#3]
moving issue from [https://github.com/TyOverby/bincode/issues/22](https://github.com/TyOverby/bincode/issues/22) to here, because I'm blind apparently; sorry for confusion!

**Comment by TyOverby** [comment]
Alright, I fixed this!

The issue was that previously for a type to be `Send`, it was _required_ to also be `'static`.  Now this is no longer the case, but channels still require the `'static` bound.  So you were never really allowed to send non-static types anyway, it's just that now it is more explicit.

**Comment by viperscape** [comment]
sweet! thanks for looking in to this
